project_name: sstart

builds:
  - id: sstart-linux-amd64
    main: ./cmd/sstart
    binary: sstart
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CGO_LDFLAGS=-lm
    ldflags:
      - -s -w
      - -X github.com/dirathea/sstart/internal/cli.version={{.Version}}
      - -X github.com/dirathea/sstart/internal/cli.commit={{.Commit}}
      - -X github.com/dirathea/sstart/internal/cli.date={{.Date}}
  - id: sstart-linux-arm64
    main: ./cmd/sstart
    binary: sstart
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
      - CGO_LDFLAGS=-lm
    ldflags:
      - -s -w
      - -X github.com/dirathea/sstart/internal/cli.version={{.Version}}
      - -X github.com/dirathea/sstart/internal/cli.commit={{.Commit}}
      - -X github.com/dirathea/sstart/internal/cli.date={{.Date}}
  - id: sstart-darwin-amd64
    main: ./cmd/sstart
    binary: sstart
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CGO_LDFLAGS=-lm
    ldflags:
      - -s -w
      - -X github.com/dirathea/sstart/internal/cli.version={{.Version}}
      - -X github.com/dirathea/sstart/internal/cli.commit={{.Commit}}
      - -X github.com/dirathea/sstart/internal/cli.date={{.Date}}
  - id: sstart-darwin-arm64
    main: ./cmd/sstart
    binary: sstart
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
      - CGO_LDFLAGS=-lm
    ldflags:
      - -s -w
      - -X github.com/dirathea/sstart/internal/cli.version={{.Version}}
      - -X github.com/dirathea/sstart/internal/cli.commit={{.Commit}}
      - -X github.com/dirathea/sstart/internal/cli.date={{.Date}}
  - id: sstart-windows-amd64
    main: ./cmd/sstart
    binary: sstart
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CGO_LDFLAGS=-lm
    ldflags:
      - -s -w
      - -X github.com/dirathea/sstart/internal/cli.version={{.Version}}
      - -X github.com/dirathea/sstart/internal/cli.commit={{.Commit}}
      - -X github.com/dirathea/sstart/internal/cli.date={{.Date}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: dirathea
    name: sstart
  mode: replace
  header: |
    ## {{ .Tag }}
    {{ if .ReleaseNotes }}
    {{ .ReleaseNotes }}
    {{ else }}
    Release {{ .Tag }}
    {{ end }}

